"""Git operations and GitHub PR creation.

Handles branching, committing, pushing, and opening a pull request via
the GitHub REST API (PyGithub).
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

from github import Github

from .config import BASE_BRANCH, BRANCH_PREFIX

logger = logging.getLogger(__name__)


def _run_git(repo_path: str, *args: str) -> str:
    """Run a git command inside the repo and return stdout."""
    result = subprocess.run(
        ["git", *args],
        cwd=repo_path,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout.strip()


def create_pull_request(
    repo_path: str,
    github_token: str,
    repo_owner: str,
    repo_name: str,
    ticket_key: str,
    ticket_summary: str,
    change_summary: str,
    files_changed: list[str],
) -> str:
    """Commit local changes, push a new branch, and open a GitHub PR.

    Parameters
    ----------
    repo_path : str
        Absolute path to the locally cloned repo.
    github_token : str
        GitHub personal access token (needs ``repo`` scope).
    repo_owner : str
        GitHub org or username that owns the repo.
    repo_name : str
        Name of the GitHub repository.
    ticket_key : str
        Jira ticket key, e.g. ``PROJ-123``.
    ticket_summary : str
        One-line summary from the Jira ticket.
    change_summary : str
        AI-generated summary of all changes.
    files_changed : list[str]
        List of file paths that were modified.

    Returns
    -------
    str
        The URL of the newly created pull request.
    """
    branch_name = f"{BRANCH_PREFIX}/{ticket_key.lower().replace(' ', '-')}"
    commit_message = f"[{ticket_key}] {ticket_summary}"

    # --- Git operations ---
    logger.info("Creating branch: %s", branch_name)
    _run_git(repo_path, "checkout", "-b", branch_name)

    logger.info("Staging all changes...")
    _run_git(repo_path, "add", ".")

    logger.info("Committing: %s", commit_message)
    _run_git(repo_path, "commit", "-m", commit_message)

    logger.info("Pushing branch to origin...")
    _run_git(repo_path, "push", "origin", branch_name)

    # --- Create PR via GitHub API ---
    logger.info("Creating pull request on %s/%s...", repo_owner, repo_name)

    files_list = "\n".join(f"- `{f}`" for f in files_changed) if files_changed else "- (none tracked)"

    pr_body = (
        f"## AI-Generated Changes for {ticket_key}\n\n"
        f"**Jira Ticket:** {ticket_key} — {ticket_summary}\n\n"
        f"### Summary of Changes\n\n"
        f"{change_summary}\n\n"
        f"### Files Changed\n\n"
        f"{files_list}\n\n"
        f"---\n"
        f"*This PR was automatically generated by the Bedrock Code Agent.*"
    )

    gh = Github(github_token)
    repo = gh.get_repo(f"{repo_owner}/{repo_name}")

    pr = repo.create_pull(
        title=commit_message,
        body=pr_body,
        head=branch_name,
        base=BASE_BRANCH,
    )

    logger.info("PR created: %s", pr.html_url)
    return pr.html_url

